name: Build and test
on:
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with: {python-version: "3.12"}

      - name: Install this project
        run: |
          pip install -U pip setuptools
          pip install .[dev]

      - name: Run tests
        run: make test

      - name: Create a native binary
        run: make binary
